"use client";

export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen flex flex-col bg-white">
      <section className="py-10 md:py-16 bg-white px-2 sm:px-4 max-w-4xl mx-auto w-full">
        <h1 className="text-3xl sm:text-4xl md:text-5xl font-bold mb-8 font-serif text-center">Privacy Policy</h1>
        <p className="mb-6 text-lg font-serif">This privacy policy (&quot;Privacy Policy&quot;) sets forth a full and complete statement of the privacy related practices and procedures adopted by Geek Services for its services under Geek Services. This Policy is effective as of the date set forth above, and will remain in effect and updated as this Policy provides. This Privacy Policy is an integral part of the Terms and Conditions posted at <a href="https://www.geek-services.com/privacy-policy.php" className="text-blue-700 underline" target="_blank" rel="noopener noreferrer">www.geek-services.com/privacy-policy.php</a>.</p>
        <h2 className="text-2xl sm:text-3xl font-bold mt-8 mb-4 font-serif">Definitions</h2>
        <p className="mb-4 text-lg font-serif">All terms initially capitalized shall have the meaning set forth in the Terms and Conditions, of which this Privacy Policy is an integral part.</p>
        <h2 className="text-2xl sm:text-3xl font-bold mt-8 mb-4 font-serif">Application</h2>
        <p className="mb-4 text-lg font-serif">Geek Services aims at resolving/providing onsite &amp; online solutions to different queries/problems that users of personal computers and peripherals may encounter while using it. The users of this service while creating their profile on the Portal for this purpose may be parting with their personal details/information. This Policy is to communicate that we respect your privacy, and we assure you that we will maintain and use this information responsibly. This policy applies to persons employed by or otherwise affiliated with Geek Services&apos;s customers, prospective customers, any persons that visit Geek Services&apos;s web site, persons who receive commercial communications sent on behalf of Geek Services, and persons submitting employment inquiries to Geek Services. This Policy does not apply to persons employed by Geek Services. We agree not to process personal information in a way that is incompatible with the purposes for which it has been collected or authorized by the users.</p>
        <h2 className="text-2xl sm:text-3xl font-bold mt-8 mb-4 font-serif">Form of Information</h2>
        <p className="mb-4 text-lg font-serif">This Policy applies to information that is obtained by Geek Services whether through electronic or print communications. Geek Services respects your privacy and is committed to protect the personal information that you share with us. Geek Services requests certain Personal Information as identified herein. Do not provide Geek Services with additional Personal Information unless you are requested to do so.</p>
        <h2 className="text-2xl sm:text-3xl font-bold mt-8 mb-4 font-serif">Personal Information</h2>
        <p className="mb-4 text-lg font-serif">&apos;Personal information&apos; means any information relating to an identified natural person, or a natural person that can be identified directly or indirectly, by reference to an identification number, or one or more factors relating to physical, psychological, mental, economic, or social identity.</p>
        <h2 className="text-2xl sm:text-3xl font-bold mt-8 mb-4 font-serif">How does Geek Services gather personal information?</h2>
        <h3 className="text-xl font-bold mt-6 mb-2 font-serif">General Browsing</h3>
        <p className="mb-4 text-lg font-serif">Geek Services gathers navigational information about where you go on our Web site. This information allows us to see which areas of our website are most visited. This helps us improve the quality of visitor&apos;s online experience by recognizing and delivering more of the features, services and products our visitors prefer. Additional non-personally identifiable information (i.e. domain type, browser version, service provider and IP address) may be collected which will provide information regarding your use of our Web site (such as the time of your last visit to a page on our site).</p>
        <h3 className="text-xl font-bold mt-6 mb-2 font-serif">Registration and Transactions</h3>
        <p className="mb-4 text-lg font-serif">Any information you provide to us at this site when you establish or update an account, purchase service plans online or request information (i.e. name, address, e-mail address and telephone number), is maintained in private files on our secure Web server and our internal systems. This information is used to enable Geek Services to deliver services to you. Geek Services and its employees do not entertain the credit card information in any form of communication on any of the media (website, chat, testimonial, remote support, email and voice). Geek Services neither stores nor publishes your credit card number on any of the media form on its server.</p>
        <h3 className="text-xl font-bold mt-6 mb-2 font-serif">System information</h3>
        <p className="mb-4 text-lg font-serif">Geek Services do not access any personal information (such as the contents of personal documents or web browsing history) stored on a PC. The data collected from the PC includes items such as: System board, BIOS, CPU, video, and memory configuration; Disk drives, disk controllers, and installed hardware; System name &amp; IP, Windows version, and browser type; System status such as CPU load and available disk space; Programs running during testing.</p>
        <h3 className="text-xl font-bold mt-6 mb-2 font-serif">Use of Cookies</h3>
        <p className="mb-4 text-lg font-serif">Geek Services uses a browser feature known as a cookie, which assigns a unique identification to your computer. Cookies also allow Geek Services to make our site more responsive to your needs, by delivering a better and more personalized experience to you. The cookies are typically stored on your computer&apos;s hard drive and are used by Geek Services to help track your clicks as you go through the pages within Geek Services web site. In addition, Geek Services uses cookies to help keep track of support requests and to tell us whether you have previously visited Geek Services. This allows registered users to avoid re-entering information upon every new visit to our site.</p>
        <h2 className="text-2xl sm:text-3xl font-bold mt-8 mb-4 font-serif">Does Geek Services disclose your personal identifiable information?</h2>
        <p className="mb-4 text-lg font-serif">You should be aware that we may disclose specific information about you if necessary to do so by law or based on our good faith belief that it is necessary to conform or comply with the law or is necessary to protect the users of our Web site, the site or the public. Geek Services does not sell, rent or trade your e-mail address to third parties. We may, however, use third parties to help us provide services to you, such as fulfilling orders, processing payments, monitoring site activity, conducting surveys, and administering e-mails. If personally identifiable information (i.e. name, address, e-mail address, telephone number) is provided to any of these third parties, we will require that such information be maintained by them in strictest confidence.</p>
        <h2 className="text-2xl sm:text-3xl font-bold mt-8 mb-4 font-serif">What are my responsibilities in protecting my personal information?</h2>
        <h3 className="text-xl font-bold mt-6 mb-2 font-serif">Member account, password and security</h3>
        <p className="mb-4 text-lg font-serif">If any of the Services requires you to open an account, you must complete the registration process by providing us with current, complete and accurate information as prompted by the applicable registration form. You also will choose a password and a user name. You are entirely responsible for maintaining the confidentiality of your password and account. Furthermore, you are entirely responsible for any and all activities that occur under your account. You agree to notify Geek Services immediately of any unauthorized use of your account or any other breach of security. Geek Services will not be liable for any loss that you may incur as a result of someone else using your password or account, either with or without your knowledge. However, you could be held liable for losses incurred by Geek Services or another party due to someone else using your account or password. You may not use anyone else&apos;s account at any time, without the permission of the account holder. We prefer to keep your personal information accurate and up-to-date. To do this, we provide you with the opportunity to update or modify your personal information including billing and shipping information by logging into your account. When you create or change your account, we will send a message to the email address confirming the changes made and options you have chosen. Geek Services periodically distributes an e-mail newsletter, and you choose whether you want to receive a newsletter from us when you create your account. If you later decide not to receive the newsletter, you can remove yourself from the mailing list at any time.</p>
        <h3 className="text-xl font-bold mt-6 mb-2 font-serif">Forgotten, Lost or Stolen Information</h3>
        <p className="mb-4 text-lg font-serif">If you have forgotten your password, we provide a mechanism that e-mails your password to you. Since the &quot;forgot my password&quot; feature sends your password to the email address that you used for registration, do not use an email address that can be accessed by others that you would not want to see or change your Geek Services account information. Always use caution when giving out any personally identifiable information about yourself or your children in any Communication Services. Geek Services does not control or endorse the content, messages or information found in any Communication Services and, therefore, Geek Services specifically disclaims any liability with regard to the Communication Services and any actions resulting from your participation in any Communication Services. Managers and hosts are not authorized Geek Services spokespersons, and their views do not necessarily reflect those of Geek Services.</p>
        <h2 className="text-2xl sm:text-3xl font-bold mt-8 mb-4 font-serif">What Are the Other Key Elements of Geek Services Privacy Policy?</h2>
        <h3 className="text-xl font-bold mt-6 mb-2 font-serif">Onward Transfer</h3>
        <p className="mb-4 text-lg font-serif">Geek Services may transfer your Personal Information to a third party that is acting as Geek Services&apos;s agent, where it makes sure that the third party provide at least the same level of privacy protection as is required by the relevant principles or applicable law.</p>
        <h3 className="text-xl font-bold mt-6 mb-2 font-serif">Access</h3>
        <p className="mb-4 text-lg font-serif">Geek Services provides individuals with access to the Personal Information about them that Geek Services holds. Geek Services agrees that individuals may correct, amend, or delete that information where it is inaccurate, except where the burden or expense of providing access would be disproportionate to the risks to the individual&apos;s privacy in the case in question, or where the rights of persons other than the individual would be violated.</p>
        <h3 className="text-xl font-bold mt-6 mb-2 font-serif">Security</h3>
        <p className="mb-4 text-lg font-serif">Geek Services takes reasonable precautions to protect Personal Information from loss, misuse and unauthorized access, disclosure, alteration and destruction. Geek Services&apos;s website has safeguards in place to protect the loss, misuse and alteration of the data you provide to us with physical, electronic, and managerial procedures. In certain areas of Geek Services&apos;s website, Geek Services uses industry-standard SSL-encryption to enhance the security of data transmissions. While Geek Services strives to protect your Personal Information, Geek Services cannot guarantee the security of the Personal Information, so Geek Services urges you to take every precaution to protect your personal data when you are on the Internet. Change your passwords often, use a combination of letters and numbers, and make sure you use a secure browser. Within Geek Services, data is stored in controlled servers with limited access by authorized personnel…</p>
        <h3 className="text-xl font-bold mt-6 mb-2 font-serif">Data Integrity</h3>
        <p className="mb-4 text-lg font-serif">Geek Services will collect Personal information that is relevant for the purposes for which it is to be used. Geek Services takes reasonable steps to ensure that data is reliable for its intended use, accurate, complete, and current.</p>
        <h3 className="text-xl font-bold mt-6 mb-2 font-serif">Third Party Sites</h3>
        <p className="mb-4 text-lg font-serif">Geek Services&apos;s website contains links to other sites operated or maintained by third parties. We are not responsible for the privacy practices or the content of such website. We will not share your personal information with third parties websites. Some of these third-party sites may be co-branded with a Geek Services logo, even though they are not operated or maintained by us. Although Geek Services chooses its business partners carefully, Geek Services is not responsible for the privacy practices of websites operated by third parties. We encourage you to learn about the privacy policies of third party or co-branded websites.</p>
        <h3 className="text-xl font-bold mt-6 mb-2 font-serif">Contact Us</h3>
        <p className="mb-4 text-lg font-serif">If you have any questions about this Privacy Policy or this website, or wish to review or update your Personal Information, then please email us at <a href="mailto:privacy@geek-services.com" className="text-blue-700 underline">privacy@geek-services.com</a></p>
        <h3 className="text-xl font-bold mt-6 mb-2 font-serif">Enforcement</h3>
        <p className="mb-4 text-lg font-serif">Geek Services periodically verifies that the policy is accurate, comprehensive for the information intended to be covered, prominently displayed, completely implemented, and in conformity with applicable privacy laws. We encourage interested persons to raise any concerns with us using the contact information above. We will investigate and attempt to resolve complaints and disputes regarding use and disclosure of Personal Information in accordance with the principles contained in this Policy. As an initial matter, Geek Services shall address each individual complaint regarding Geek Services compliance with this Policy.</p>
        <h3 className="text-xl font-bold mt-6 mb-2 font-serif">Data Integrity</h3>
        <p className="mb-4 text-lg font-serif">Geek Services will collect Personal information that is relevant for the purposes for which it is to be used. Geek Services takes reasonable steps to ensure that data is reliable for its intended use, accurate, complete, and current.</p>
        <h2 className="text-2xl sm:text-3xl font-bold mt-8 mb-4 font-serif">Changes to this Privacy Policy</h2>
        <p className="mb-4 text-lg font-serif">We reserve the right, at any time and without notice, to update or otherwise modify this Privacy Policy by posting such update or other modification at the Privacy Policy page on the Website. Any update or other modification shall be effective immediately upon such posting. Accordingly, we encourage you to review this Privacy Policy periodically to determine if it has been modified.</p>
      </section>
    </div>
  );
} 